using System.Text;
using TFWR.Compiler.Ir;

namespace TFWR.Compiler.Emit;

/// <summary>
/// Emits TFWR IR modules as Python source text.
/// </summary>
public sealed class TfwrEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;

    /// <summary>
    /// Emits a single module as Python source.
    /// </summary>
    /// <param name="module">IR module to emit.</param>
    /// <returns>Generated Python source text.</returns>
    public string Emit(TfwrModule module)
    {
        _sb.Clear();
        _indent = 0;

        _sb.AppendLine("# Generated by tfwrc - do not edit by hand.");
        _sb.AppendLine();

        foreach (var import in module.Imports.Distinct().OrderBy(x => x, StringComparer.Ordinal))
        {
            _sb.Append("import ").AppendLine(import);
        }

        if (module.Imports.Count > 0)
        {
            _sb.AppendLine();
        }

        foreach (var fn in module.Functions)
        {
            EmitFunction(fn);
            _sb.AppendLine();
        }

        foreach (var stmt in module.TopLevelStatements)
        {
            EmitStmt(stmt);
        }

        if (module.TopLevelStatements.Count > 0)
        {
            _sb.AppendLine();
        }

        if (module.EntryFunctionName is { } entry)
        {
            WriteLine("if __name__ == \"__main__\":");
            Indent();
            WriteLine($"{entry}()");
            Dedent();
        }

        return _sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private void EmitFunction(TfwrFunction fn)
    {
        var parameters = string.Join(", ", fn.Parameters.Select(p =>
        {
            if (p.DefaultValue is null)
            {
                return p.Name;
            }

            return $"{p.Name}={EmitExpr(p.DefaultValue)}";
        }));

        WriteLine($"def {fn.Name}({parameters}):");
        Indent();
        if (fn.Body.Count == 0)
        {
            WriteLine("pass");
        }
        else
        {
            foreach (var stmt in fn.Body)
            {
                EmitStmt(stmt);
            }
        }

        Dedent();
    }

    private void EmitStmt(TfwrStmt stmt)
    {
        switch (stmt)
        {
            case ExprStmt e:
                WriteLine(EmitExpr(e.Expression));
                break;
            case AssignStmt a:
                WriteLine($"{EmitExpr(a.Target)} = {EmitExpr(a.Value)}");
                break;
            case AugAssignStmt a:
                WriteLine($"{EmitExpr(a.Target)} {a.Op}= {EmitExpr(a.Value)}");
                break;
            case IfStmt i:
                WriteLine($"if {EmitExpr(i.Condition)}:");
                Indent();
                EmitBlock(i.ThenBody);
                Dedent();
                foreach (var (cond, body) in i.Elifs)
                {
                    WriteLine($"elif {EmitExpr(cond)}:");
                    Indent();
                    EmitBlock(body);
                    Dedent();
                }

                if (i.ElseBody is { } elseBody)
                {
                    WriteLine("else:");
                    Indent();
                    EmitBlock(elseBody);
                    Dedent();
                }

                break;
            case WhileStmt w:
                WriteLine($"while {EmitExpr(w.Condition)}:");
                Indent();
                EmitBlock(w.Body);
                Dedent();
                break;
            case ForStmt f:
                WriteLine($"for {f.Variable} in {EmitExpr(f.Iterable)}:");
                Indent();
                EmitBlock(f.Body);
                Dedent();
                break;
            case ReturnStmt r:
                WriteLine(r.Value is null ? "return" : $"return {EmitExpr(r.Value)}");
                break;
            case BreakStmt:
                WriteLine("break");
                break;
            case ContinueStmt:
                WriteLine("continue");
                break;
            case PassStmt:
                WriteLine("pass");
                break;
            case GlobalStmt g:
                WriteLine("global " + string.Join(", ", g.Names));
                break;
            default:
                throw new NotSupportedException($"Unknown statement {stmt.GetType().Name}");
        }
    }

    private void EmitBlock(List<TfwrStmt> body)
    {
        if (body.Count == 0)
        {
            WriteLine("pass");
            return;
        }

        foreach (var stmt in body)
        {
            EmitStmt(stmt);
        }
    }

    private string EmitExpr(TfwrExpr expr) => expr switch
    {
        NameExpr n => n.Name,
        LiteralExpr l => l.Text,
        UnaryExpr u => u.Op is "not" ? $"not {EmitExpr(u.Operand)}" : $"{u.Op}{EmitExpr(u.Operand)}",
        BinaryExpr b => $"({EmitExpr(b.Left)} {b.Op} {EmitExpr(b.Right)})",
        CallExpr c => $"{EmitExpr(c.Callee)}({string.Join(", ", c.Arguments.Select(EmitExpr))})",
        AttributeExpr a => $"{EmitExpr(a.Target)}.{a.Name}",
        IndexExpr i => $"{EmitExpr(i.Target)}[{EmitExpr(i.Index)}]",
        ListExpr l => "[" + string.Join(", ", l.Elements.Select(EmitExpr)) + "]",
        DictExpr d => d.Entries.Count == 0
            ? "{}"
            : "{" + string.Join(", ", d.Entries.Select(e => $"{EmitExpr(e.Key)}: {EmitExpr(e.Value)}")) + "}",
        SetExpr s => s.Elements.Count == 0
            ? "set()"
            : "{" + string.Join(", ", s.Elements.Select(EmitExpr)) + "}",
        TupleExpr t => t.Elements.Count switch
        {
            0 => "()",
            1 => $"({EmitExpr(t.Elements[0])},)",
            _ => "(" + string.Join(", ", t.Elements.Select(EmitExpr)) + ")"
        },
        ConditionalExpr => throw new InvalidOperationException("ConditionalExpr must be lowered before emit."),
        _ => throw new NotSupportedException($"Unknown expression {expr.GetType().Name}")
    };

    private void WriteLine(string line)
    {
        _sb.Append(new string(' ', _indent * 4));
        _sb.AppendLine(line);
    }

    private void Indent() => _indent++;
    private void Dedent() => _indent--;
}
