<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\TFWR.Api\TFWR.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
		<PackageReference Include="Basic.Reference.Assemblies.Net100" Version="1.8.11" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.1</Version>
		<Authors>SeongSikChae</Authors>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RepositoryUrl>https://github.com/SeongSikChae/TFWRCompilier.NET.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/SeongSikChae/TFWRCompilier.NET.git</PackageProjectUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
